language: objective-c
osx_image: xcode8

before_install:
  - gem install xcpretty
  
script:
  - set -o pipefail && xcodebuild clean build test -project Test/Thread.xcodeproj -scheme "ThreadOSX" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild test -project Test/Thread.xcodeproj -scheme "ThreadOSX" | xcpretty